# Draft MAKEFILE

all : data/raw/license_data.csv

data/raw/license_data.csv : src/get_license_data.py
	python src/get_license_data.py --target_file=data/raw/license_data.csv

data/raw/linked_corp_data.csv : src/get_linked_corp_data.py
	python src/get_linked_corp_data.py --target_file=data/raw/linked_corp_data.csv